version: "3.7"
services:
  app:
    build:
      context: ./
      dockerfile: ./docker/Dockerfile.dev
    volumes:
      - "./src:/var/www/html"
    ports:
      - "8000:80"
    restart: on-failure
    networks:
      - app

networks:
  app:
    driver: bridge
